import type { Metadata } from "next"

import "./globals.css"
import { hankenGrotesk } from "@/lib/font"
import { TxToaster } from "@/components/TxToaster"
import { SorobanProvider } from "@/lib/soroban/SorobanContext"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${hankenGrotesk.variable} antialiased`} suppressHydrationWarning>
        <Providers>
          <SorobanProvider>
            <TxToaster />
            {children}
          </SorobanProvider>
        </Providers>
      </body>
    </html>
  )
}

