import type { Metadata } from "next"

import "./globals.css"
import { hankenGrotesk } from "@/lib/font"
import { TxToaster } from "@/components/TxToaster"
import Providers from "./providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${hankenGrotesk.variable} antialiased`} suppressHydrationWarning>
        <Providers>
          <TxToaster />
          {children}
        </Providers>
      </body>
    </html>
  )
}

